// Dados centralizados. Fonte: NASA / IAU Minor Planet Center (luas verificadas em 2026).
const planets = {
  sun:{nome:"Sol",tipo:"Estrela central",desc:"Estrela anã amarela composta principalmente por hidrogénio e hélio. Concentra cerca de 99,86% de toda a massa do Sistema Solar.",luas:"—",grav:"≈ 274 m/s²",gravRel:"cerca de 28× a da Terra",dist:"Distância média: ≈ 149,6 milhões km (1 UA)",fonte:"NASA"},
  moon:{nome:"Lua",tipo:"Satélite natural da Terra",desc:"O único satélite natural da Terra e o único corpo, além do nosso planeta, onde já pisaram seres humanos. Roda ao mesmo ritmo a que orbita a Terra, por isso mostra-nos sempre a mesma face. Tem uma atmosfera (exosfera) muito ténue.",luas:"0 (a Lua não tem luas)",grav:"≈ 1,62 m/s²",gravRel:"cerca de 1/6 da Terra",dist:"Média: ≈ 384 400 km · Varia entre ≈ 360 000 e ≈ 405 000 km",fonte:"NASA"},
  mercury:{nome:"Mercúrio",tipo:"Planeta rochoso",desc:"O menor planeta do Sistema Solar e o mais próximo do Sol. A superfície é rochosa e cheia de crateras, sem atmosfera significativa para reter calor.",luas:"0",grav:"≈ 3,7 m/s²",gravRel:"38% da Terra",dist:"Média: ≈ 91,7 milhões km · Mínima: ≈ 77 milhões km",fonte:"NASA",orbit:22,size:1.5,secs:24},
  venus:{nome:"Vénus",tipo:"Planeta rochoso",desc:"Tem tamanho semelhante ao da Terra e uma atmosfera densa de dióxido de carbono, com nuvens de ácido sulfúrico, que causa o efeito de estufa mais intenso do Sistema Solar.",luas:"0",grav:"≈ 8,87 m/s²",gravRel:"90% da Terra",dist:"Média: ≈ 41,4 milhões km · Mínima: ≈ 38 milhões km",fonte:"NASA",orbit:32,size:2.4,secs:38},
  earth:{nome:"Terra",tipo:"Planeta rochoso",desc:"O nosso planeta natal e o único corpo celeste conhecido que abriga vida. Tem água líquida na superfície e uma atmosfera rica em azoto e oxigénio.",luas:"1 (a Lua)",grav:"≈ 9,81 m/s²",gravRel:"referência",dist:"0 km (é onde estamos)",fonte:"NASA",orbit:42,size:2.6,secs:52},
  mars:{nome:"Marte",tipo:"Planeta rochoso",desc:"O Planeta Vermelho, com solo rico em óxido de ferro. Tem atmosfera fina, vales, vulcões extintos (como o Monte Olimpo) e calotas polares de gelo de água e dióxido de carbono.",luas:"2 (Fobos e Deimos)",grav:"≈ 3,71 m/s²",gravRel:"38% da Terra",dist:"Média: ≈ 225 milhões km · Mínima: ≈ 54,6 milhões km",fonte:"NASA",orbit:52,size:2,secs:70},
  jupiter:{nome:"Júpiter",tipo:"Gigante gasoso",desc:"O maior planeta do Sistema Solar, composto sobretudo por hidrogénio e hélio. É famoso pela Grande Mancha Vermelha, uma tempestade gigante.",luas:"101 confirmadas (Io, Europa, Ganimedes)",grav:"≈ 24,79 m/s²",gravRel:"2,5× a da Terra",dist:"Média: ≈ 628,7 milhões km · Mínima: ≈ 588 milhões km",fonte:"NASA / IAU MPC, mar. 2026",orbit:64,size:5.4,secs:95},
  saturn:{nome:"Saturno",tipo:"Gigante gasoso",desc:"Gigante gasoso famoso pelo complexo e brilhante sistema de anéis, formados por partículas de gelo e rocha.",luas:"285 confirmadas (Encélado, Titã, Jápeto)",grav:"≈ 10,44 m/s²",gravRel:"1,06× a da Terra",dist:"Média: ≈ 1,27 mil milhões km · Mínima: ≈ 1,2 mil milhões km",fonte:"NASA / IAU MPC, mar. 2026",orbit:76,size:4.6,secs:120},
  uranus:{nome:"Urano",tipo:"Gigante gelado",desc:"Gigante gelado de cor azul-esverdeada, devido ao metano na atmosfera. Orbita “deitado”, com o eixo de rotação inclinado cerca de 98°.",luas:"29 confirmadas (Titânia, Ariel, Umbriel)",grav:"≈ 8,69 m/s²",gravRel:"89% da Terra",dist:"Média: ≈ 2,72 mil milhões km · Mínima: ≈ 2,6 mil milhões km",fonte:"NASA / Sky & Telescope, nov. 2025",orbit:88,size:3.6,secs:150},
  neptune:{nome:"Neptuno",tipo:"Gigante gelado",desc:"O planeta mais distante do Sol, também um gigante gelado. Tem cor azul intensa e os ventos mais rápidos do Sistema Solar, acima de 2000 km/h.",luas:"16 confirmadas (Tritão, Proteu)",grav:"≈ 11,15 m/s²",gravRel:"1,14× a da Terra",dist:"Média: ≈ 4,35 mil milhões km · Mínima: ≈ 4,3 mil milhões km",fonte:"NASA",orbit:98,size:3.5,secs:180}
};
const students = ["Alicio da Costa","Anderson Caldas","Juliana Selesu","Ster Muhongo","Artur Fortunato","Daniela Ventura","Denzel Cristovão","Edson da Rocha","Gabriel Luis","Ismael Piedade","Ilídio Quingolo","Landercia António","Mário de Sousa","Royani Nóbrega","Teresa Menezes","William Airosa","Clayton Guimarães","Severino Nanga"];
